name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/ -v --tb=short

  docker:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker compose -f docker/docker-compose.yaml -p audio-api up -d

  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: [test, docker]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Start API server
      run: |
        python -m uvicorn app.main:app --host 0.0.0.0 --port 5000 &
        sleep 5
    
    - name: Test API endpoints
      run: |
        curl -f http://localhost:5000/health
        curl -f "http://localhost:5000/list?user_id=test" | grep -q '"count":0'
        echo "All integration tests passed!"
    
    - name: Stop server
      run: |
        pkill -f uvicorn || true
